owner: BradleyBao 
repo: uptime

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

status-website:
  cname: status.tianyibrad.com
  # baseUrl: /repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Services Status
  introTitle: "tianyibrad Infra Status"
  introMessage: Real-time service health and incident reports.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://www.tianyibrad.com
